name: Deploy Coverage Reports

on:
  workflow_run:
    workflows: ["CI - Java Spring Boot"] # Nome do workflow de CI
    branches:
      - '**' # Aciona para qualquer branch
    types:
      - completed

jobs:
  deploy-coverage:
    name: Deploy Coverage Reports
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
    steps:
      # Checkout do repositório
      - name: Checkout
        uses: actions/checkout@v4

      # Configurar o JDK 17
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      # Compilar e gerar o relatório de cobertura
      - name: Build and Generate Coverage Report
        run: |
          mvn clean package jacoco:report

      # Copiar os relatórios gerados para o diretório staging
      - name: Prepare Coverage Report for Deployment
        run: mkdir staging && cp -r target/site/jacoco staging/

      # Fazer o upload do relatório gerado como artefato
      - uses: actions/upload-artifact@v4
        with:
          name: Coverage Report
          path: staging

      # Deploy do relatório no branch "cov"
      - name: Deploy Coverage Reports to gh-pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: cov
          publish_dir: staging/jacoco
