name: Deploy Coverage Reports

on:
  workflow_run:
    workflows: ["CI"] # Nome correto do workflow de CI
    branches:
      - '**' # Aciona para qualquer branch
    types:
      - completed

jobs:
  deploy-coverage:
    name: Deploy Coverage Reports
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # Apenas se o CI for bem-sucedido
    permissions:
      contents: write
    steps:
      # Log para depuração: Verifica o status do evento `workflow_run`
      - name: Log event data
        run:
          echo "Event data: ${{ github.event }}"

      # Checkout do repositório
      - name: Checkout
        uses: actions/checkout@v4

      # Configurar o JDK 17
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64

      # Compilar e gerar o relatório de cobertura
      - name: Build and Generate Coverage Report
        run: |
          mvn clean package jacoco:report

      # Preparar os relatórios gerados para o deployment
      - name: Prepare Coverage Report for Deployment
        run: mkdir -p staging/jacoco && cp -r target/site/jacoco/* staging/jacoco/

      # Deploy para o branch "cov"
      - name: Deploy Coverage Reports to cov branch
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: cov
          publish_dir: staging/jacoco
