name: Unit tests

on:
  push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn --batch-mode test
